### ISSUE TITLE
Crash while zooming on Nexus 6P

### ISSUE THREAD

**Issue by davebren** [asakaplan/Fractal-Generator#1]
09-09 15:05:40.809 12996-12996/toptal.git.fractalgenerator E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: toptal.git.fractalgenerator, PID: 12996
                                                                             java.lang.IllegalArgumentException: pointerIndex out of range
                                                                                 at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                                 at android.view.MotionEvent.getX(MotionEvent.java:2057)
                                                                                 at toptal.git.fractalgenerator.FractalSurfaceView.onTouchEvent(FractalSurfaceView.java:59)
                                                                                 at android.view.View.dispatchTouchEvent(View.java:9294)

**Comment by willowkap** [comment]
Thanks, should be fixed in the most recent version. The app bugged when more than 2 fingers were being used.
